# PBS flags
queue: normal
walltime: 2:00:00
ncpus: 480
# mem: 64GB

# mpirun:
#    - --bind-to none

jobname: benchmark

# Model config
model: cable
exe: /g/data/w35/ccc561/CABLE/Metvar-lookup1/offline/cable-mpi
input: 
    - /scratch/w35/ccc561/CABLE/CABLE_benchmarking/input_dir
    - /scratch/p66/yxw599/runcable-access-esm/gswp/system3/
    - /scratch/p66/yxw599/runcable-access-esm/inputs/

collate: False

runspersub: 2

restart: /scratch/v45/aph502/cable/restart/test
