format: yamanifest
version: 1.0
---
work/INPUT/cable.res.yaml:
  fullpath: /scratch/v45/aph502/cable/archive/test/restart006/cable.res.yaml
  hashes:
    binhash: 878f4327588ba437afb109fc579afb3b
    md5: ef3a41154d7e7d2f1351c61bb9675e67
work/INPUT/restart.nc:
  fullpath: /scratch/v45/aph502/cable/archive/test/restart006/restart.nc
  hashes:
    binhash: ed11c8f02c33beeac11ce00ab76e3f5c
    md5: 485f214c495d9a0bc1421b569725fc75
