format: yamanifest
version: 1.0
---
work/INPUT/restart.nc:
  fullpath: /scratch/v45/aph502/cable/archive/test/restart003/restart.nc
  hashes:
    binhash: 62e5167d0ec28020fe3dbe9b381fcd14
    md5: 4e815c3de5d78939f52b5dca8c3507e5
